plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.11'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '7.2.1'
}

group = 'com.reverse'
version = '0.0.1-SNAPSHOT'
description = 'rhight-backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springModulithVersion', "1.4.8")
}

spotless {
    java {
        // 적용할 파일 범위 지정
        target '**/src/*/java/**/*.java'

        // 1. 구글 자바 포맷 적용 (AOSP 스타일은 4스페이스를 사용해 윈도우/맥 가독성이 좋습니다)
        googleJavaFormat().aosp()

        // 2. 사용하지 않는 import 제거
        removeUnusedImports()

        // 3. 공통 스타일 규칙
        trimTrailingWhitespace()   // 줄 끝 공백 제거
        endWithNewline()           // 파일 끝에 빈 줄 추가

    }
}

dependencies {
    implementation 'org.springframework.modulith:spring-modulith-starter-core'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('installLocalGitHook', Copy) {
    description = 'scripts 폴더의 pre-commit 파일을 .git/hooks로 복사하고 실행 권한을 부여합니다.'

    from new File(rootProject.rootDir, 'scripts/pre-commit')
    into { new File(rootProject.rootDir, '.git/hooks') }

    // 이 한 줄이 사진의 'makeGitHooksExecutable' 태스크 역할을 대신합니다.
    fileMode 0775
}

// 빌드 전체보다는 컴파일 단계에 연결하는 것이 더 효율적입니다.
tasks.named('compileJava') {
    dependsOn 'installLocalGitHook'
}

bootJar {
    enabled = false // 실행 가능한 jar 생성 금지 (메인 클래스 없어도 됨)
}

jar {
    enabled = true  // 다른 모듈이 참조할 수 있는 일반 jar 파일 생성
}
