spring:
  application:
    name: rhight-backend

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:./api/.env[.properties]

  #  local? ????
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  # Spring Modulith ?? ??
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

security:
  hash:
    pepper: ${SECURITY_HASH_PEPPER}
  enc:
    key-base64: ${SECURITY_ENC_KEY_BASE64}
  cors:
    allowed-origins:
      http://localhost:8080
      http://api.beyond21.iptime.org
      
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
