spring:
  sql:
    init:
      mode: always  # 기본값인 embedded 대신 always로 설정해야 MariaDB에서 작동함
  config:
    activate:
      on-profile: local

mybatis:
  mapper-locations: classpath:mapper/*.xml # xml 파일 경로
  configuration:
    map-underscore-to-camel-case: true

  datasource:
    url: jdbc:mariadb://beyond21.iptime.org:2101/rhight
    driver-class-name: org.mariadb.jdbc.Driver
    username: reverse
    password: reverse

#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        highlight_sql: true
#        format_sql: true
#        use_sql_comments: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

s3:
  endpoint: http://localhost:9000
  access-key: avcTUqjJqwNPVy0F5ZQT
  secret-key: 6WsJAnE0BOCLnuH3eqZRHgy6atv7wOHOLpAttCdE

jwt:
  secret: "c0VOKXLQX/2HmTKN0fkmqy1mf0EuTCUVrqzcDjIMnqIuBtufqFEfi9Ihnl+2OfxoPrn78+wM25yn2dwKsUy/LA=="
  expiration: 1800000
  refresh-expiration: 604800000